name: Markdown to PDF
on: push

jobs:
  markdown_to_pdf:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.11.4'
      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Compile PDFs
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }} ${{ steps.files.outputs.renamed }}; do
            output="${changed_file%.*}.pdf"
            if [[ $changed_file == *.md && -f $output ]]; then
              echo "Converting file $changed_file"
              pandoc --resource-path=`dirname $changed_file`:. --pdf-engine=tectonic -N -o $output $changed_file
            fi
          done
      - name: Upload PDFs
        if: ${{ success() }}
        run: |
          git status
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git ls-files --modified | xargs git add
          if git diff --cached --exit-code; then
            echo "Exiting because no files are added"
            exit 0
          fi
          GIT_SHORTSHA=$(echo "$GITHUB_SHA" | cut -c 1-8)
          git commit -m "Generate PDFs for $GIT_SHORTSHA"
          git push
        
